url: http://csinva.github.io
baseurl: ""

# Site Settings
title: Chandan Singh
description: "Chandan Singh Homepage"
keywords: "Chandan, Singh, Computer Science"
collections:
 notes:
    name: Notes
    documentation: https://github.com/Shopify/liquid/wiki/Liquid-for-Designers
    output: true
markdown: kramdown
exclude: ["Rakefile", "LICENSE", "readme.markdown"]